idf_component_register(
    SRCS
        "main.c"
        "bsp_display.c"
        "display_comm.c"
        "ui_screens.c"
    INCLUDE_DIRS
        "../include"
        "."
    REQUIRES
        driver
        esp_lcd
        esp_timer
        esp_lvgl_port
        lvgl
        esp_lcd_touch_gt911
        json
)
