; PlatformIO Project Configuration - Medic-Bot Main Controller (C++ Native ESP-IDF)
; Board: ESP32-S3 USB OTG (8MB Flash)
; Framework: ESP-IDF

[env:esp32s3usbotg]
platform = espressif32@6.9.0
board = esp32s3usbotg
framework = espidf
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
